### PR TITLE
Add support for reftex-derived categories

### PR DESCRIPTION
**Pull request by swflint**
This should start towards #4 (there are still a few kinks to be worked out with respect to showing context, but that may be easy enough).

### CODE REVIEW

**Comment by karthink** [comment]
Thanks!

> there are still a few kinks to be worked out with respect to showing context, but that may be easy enough

Are you planning to add more commits to this PR?

**Comment by swflint** [comment]
Probably.  That being said, it may make more sense to merge this and I can try and fix the context-finding for non-standard types (where I was seeing the problems).

**Comment by swflint** [comment]
My prior issue appears to be because the document was due for a reparse.  It seems that context finding should already be handled.

**Comment by karthink** [comment]
Cheers @swflint!

**Pull request merged**
