### PR TITLE
Clean code up (conform to check-doc & package-lint)

### PR DESCRIPTION
**Pull request by swflint**
This PR cleans code up so that it passes (most) check-doc and package-lint checks.
I hope that this can help move the package to something submittable to MELPA.

### CODE REVIEW

**Comment by karthink** [comment]
@swflint I merged the other PRs before this one.  Could you rebase this branch on top of the other changes so I can merge this one too?

**Comment by swflint** [comment]
Will do!

**Comment by swflint** [comment]
It should be closer to ready.  There are definitely some things you ought to fill in yet (License information, version), however.

**Comment by swflint** [comment]
I've reorganized the code a bit (hopefully things will be a bit easier to find), added some section headers, etc.  The further reorganization should help to make it clearer how to reuse or modify existing code to add in support for citations with bibtex.

**Comment by karthink** [comment]
@swflint Much appreciated! I'll merge this now.

**Pull request merged**
